#!/bin/bash 
#This is a script to scrape lists generated by get_pets_list.sh and generate an html file for each website named for each pet
website="https://ws.petango.com/webservices/adoptablesearch"
echo $website
if [[ -f $1 ]]; then
     file=$1  
    while read line; do  
    website2=$line grep -o -P '(?<=href=").*(?=" >)'
    echo $website/$website2
    #echo "$website/$($line grep -o -P '(?<=href=").*(?=" >)')"
    #Readind each line in sequence 
    #find the name of each pet
    
    
   
    #find website on each line and save it as the pet's name
   
    #grep -o -P '(?<=href=").*(?=" >)'| wget $line | grep -o -P '(?<=css=" >).*(?=</a>)'  
    
    done < $file 
    https://ws.petango.com/webservices/adoptablesearch/wsAdoptableAnimalDetails.aspx?id=29096204&css=
 wget -O dummy_website https://ws.petango.com/webservices/adoptablesearch/wsAdoptableAnimalDetails.aspx?id=29096204&css=
fi




