#!/bin/bash 
#This is a script to scrape lists generated by get_pets_list.sh and generate an html file for each website named for each pet

if [[ -f $1 ]]; then
     file=$1  
    while read line; do  
    
    #Readind each line in sequence 
    #find the name of each pet
    petname = grep "petname in get_pets_list.sh"
    #find website on each line and save it as the pet's name
   
    grep -x "whatever we need to find the website" | wget -o petname
    done < $file 
    

fi




